name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install TCL
      run: sudo apt-get update && sudo apt-get install -y tcl

    - name: Run bake.tcl script
      run: tclsh bake.tcl
