name: Build and Deploy with ActiveTcl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-tcl-app .

    - name: Run Docker Container
      run: docker run my-tcl-app
